#!/usr/bin/env ruby
require 'json';def φ(÷);≡,‼,ε=122,{},Z*B;(ε..≡).each{|¶|¶=¶.chr;‼[÷.index(¶)]=¶};‼;end;def §(⌡,‼)#//\\/ © 2022 _//.
⌡.scan(/.{1,#{B}}/).map{|¶|‼[¶.to_i(B*Z)+1]}.join;end;⌠=nil;a=/^[ ]*([\d]{4}-?[^ ]*)[ ]*(.*)/;b=/^[ ]{20}/#022 _//.
c=/ (using|with|for|in|on|&|\/) |,'/;d=/^[ ]*$/;e=/^[ ]{15}/;B=2;"#//\\//\\//\\//\\//\\//\\//\\//\\//\\ © 2022 _//.



                                            A n d r e w    S a l v e s o n
                                            612-805-5697 andrew@artgot.com



";⌡="2l2n2p2r92979s4h2r932n9f2r2v2n9s2n2j2l2n2p2r2n2v312n9sa9922p9s7g314h2rer2r4h2r2n4l9s9f92317g4h2r922v9s4h2r4"+
"h9f2n9s972n4l319s2n2j2n317a4h2n979s7g4l207g9s4l7a2l2l922p4h2r2vai9s2p2n312n2rer2n979s4lg32r9f9f4l9s1";÷="

                                                               _
               E x p e r i e n c e                             |     E x p e r t i s e
                                                               |
               Outer Labs                                      |     Automated spatial layout
2020-present   Software Engineer - remote setting              |     
               Building layout automation                      |     Indie game design and development 
                    Full-stack web development                 |         Unity (C#)
                                                               |     
               WeWork                                          |     Spatial transformations
2018-2020      Software Engineer - New York City               |
               Design, development, and integration of         |     Server Management
               spatial data pipeline from Autodesk             |         Debian, LEDE
               Revit for internal business use                 |         Nginx, WAMP, LAMP, IIS, GeoServer
                    Plugins using .NET / Revit API with IPC    |
                    GUIs in TypeScript / React & Electron      |     Service development
                    ETL in Go on Kubernetes                    |         Go, Node, Java/Kotlin Spring Boot
                    Storage in Java / Spring Boot with AWS     |
                    APIs in Go / gRPC / PostreSQL / Kubernetes |     Front-end development
                    Observability with Jaeger / Grafana        |         Numerous JavaScript frameworks
                    Service integration in Kotlin / gRPC       | 
                    Geometric transformations in Kotlin / Go   |     Code/package management
                    CI/CD using Jenkins / Powershell / C#      |         Git, Subversion
                                                               |         NPM, NuGet, Composer
               Perkins+Will, Inc.                              |         JFrog, Quay.io
2017-2018      Software Engineer - New York City               |                                              
               Full-stack web development                      |     Database management
                    Front-end in TypeScript / Angular          |         MySQL, PostgreSQL, Neo4j, MSSQL
                    Back-end in TypeScript / Node              |         
2016-2017      Digital Practice Manager - New York City        |     Add-in and script development
               Technology project management                   |         Revit (C#, Python, Dynamo)
                    Plugins for Revit in .NET / C#             |         SketchUp (Ruby)
                    Data wrangling in Python / MSSQL           |         Adobe Creative Suite (JavaScript)
                    APIs in PHP & Node                         |         Office suite (VB)
                    Design scripts in Grasshopper & Dynamo     |         
2014-2016      Design Applications Manager - New York City     |     Deployment    
               Architectural technologist and BIM              |         Docker(machine), Kubernetes
               management                                      |         Heroku, Azure, AWS
                    GIS with GeoServer, ArcGIS, GRASS GIS      |         Travis, CircleCI, Jenkins
                    GUIs in JavaScript                         |                                              
                    Knowledge Management                       |     
                    Computational Design for Revit & Rhino     |     Miscellaneous hackery
                    Content Development/Training for Revit     |         Electronics, Linux scripting
2013-2014     Design Applications Manager - Minneapolis        |                                              
                    Architectural work                         |     Obsolete languages
                    Software and IT support                    |         ActionScript (RIP), PureData
                                                               |                                              
               Neurotinker                                     |                                              
2014           Co-founder - Minneapolis                        |     Other skills
               Neuron simulation hardware                      |         Graphic art
                    ARM32 firmware and I/O protocol            |         Music composition
                    business plan and pricing model            |         Drawing instruction
                                                               |         Writing
               Various Clients (available upon request)        |                                              
2004-present   Freelance Designer - Various locations          |     E d u c a t i o n  &  H o n o r s
               Scratching the creative itch                    |                                     
                    Furniture Design                           |     2018 Innovation Incubator Grant 
                    Graphic Design                             |     2014 Innovation Incubator Grant
                                                               |     2010 Ralph Rapson Fellowship
               Various Firms (available upon request)          |     2007 Bachelor of Science in Architecture
2010-2013      Intern Architect - Minneapolis, St. Paul        |     2003 Alworth Memorial Scholarship
               Architectural project work                      |     



";Z=B**(B*B);‼=φ(÷);♣,♠,♂,♦,☻,♥,♀,♪,♫,☺={},{},{},{},' ',⌠,⌠,⌠,⌠,'-';☼,α,ß,Γ,π,Σ,σ,µ,τ,Φ,Ω,δ,∞=§(⌡,‼).split(☺)# _//.
÷.split("\n")[5..-B].each{|≈|f,g=≈.split("|");if a.match?(g)then ♦[g[a,1]]=[] if ♦[g[a,1]].nil?#//\\//\ © 2022 _//.
♦[g[a,1]].append({δ=>g[a,B]});end;if d.match(f)then ♫=nil;next;end;if ♫.nil? and e.match?(f)then ♫=f.strip;♣[♫]={}#
elsif a.match?(f)then ♥={☼=>f[a,1],µ=>"",π=>[]};j,k=f[a,B].strip.split(☻+☺+☻);♥[σ]=j;♥[Σ]=k;♣[♫]={} if ♣[♫].nil?#/.
♣[♫][♥[☼]]=♥;elsif b.match?(f)then s=f.strip;q=s.split(c);♣[♫][♥[☼]][π]<<s;n=q[0]#//\\//\\//\\//\\//\\/ © 2022 _//.
q[1..-1].each{|r|if not ♂[r].nil? then ♂[r][n]=♫;elsif r!='' then ♂[r]={};end};♦[♥[☼]]=[] if ♦[♥[☼]].nil?#2022 _//.
♦[♥[☼]]<<{τ=>f.strip,Φ=>♥[σ],Ω=>♥[µ],Γ=>♫,"in"=>♥[Σ]};elsif not f.nil?;♣[♫][♥[☼]][µ]+=f.strip+☻;end}#// © 2022 _//.
puts(JSON.pretty_generate({ß=>♣,α=>♦,∞=>♂}));#//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\//\\/ © 2022 _//.
